### ISSUE TITLE
Please add 'varargs' support

### ISSUE THREAD

**Issue by activey** [nmelnick/Log4Vala#1]
Please consider impementing varargs in logging methods that we could pass an array of variables. This could work together with va_list().

**Comment by nmelnick** [comment]
Would you use them like printf, or expect them to just be output in some fashion?

**Comment by activey** [comment]
Yup, like printf ;)

**Comment by nmelnick** [comment]
May be worth revisiting the API a little bit. For now, I have added methods appended with _format to allow varargs support as of commit 93a5204.

**Comment by activey** [comment]
Awesome :) thx

**Comment by nmelnick** [comment]
Given that the API seems simple enough, a formal change was made in commit b5079ba -- there are now f functions (infof, warnf, etc) to provide formatting, and the _format functions are still available for use. Library has been bumped to 0.2.
